### PR TITLE
Show thread ids and names

### PR DESCRIPTION
**Pull request by oli-obk**
based on #11 

Screenshot from 2020-08-05 14-53-52

### CODE REVIEW

**Comment by davidbarsky** [comment]
Few notes:

- What do you mean by "I can't figure out how to make this work reasonably on the first event/span emitted"?
- Is the screenshot right? I'm sure I'm seeing the thread names/IDs...
- Can you rebase since I merged #11?

**Comment by oli-obk** [comment]
>     * What do you mean by "I can't figure out how to make this work reasonably on the first event/span emitted"?



If you look at the first line, there's no thread id/name preprended.... and I just realized this can't work the way I implemented it :facepalm: We'd get the thread id and name of the span/event *before* the line being emitted.

Doing this PR would require a refactoring that moves the indentation rendering to when an actual event is printed instead of doing it proactively for the next event.

**Comment by oli-obk** [comment]
Nevermind, I figured it out ^^ I just overlooked one edge case

**Comment by davidbarsky** [comment]
Nice! Thanks for this. One thing that can be done a followup: since I prefer to use narrow fonts (Pragmata Pro!), it'd be nice to give a bit of spacing between the thread name and ID and the target:
Screen Shot 2020-08-08 at 1 42 12 PM

**Comment by oli-obk** [comment]
> it'd be nice to give a bit of spacing between the thread name and ID and the target:

Do you mean just for the cases where there's no indent at all or just put a space after the thread name in general?

**Pull request merged**
